#!/bin/sh
#
# Pre-commit hook that verifies if all files containing 'vault' in the name
# are encrypted.
# If not, commit will fail with an error message
#
# File should be .git/hooks/pre-commit and executable

for hook in .git/hooks/pre-commit.d/*; do
	test -x ${hook}
	(echo "${data}" | ${hook}) || exit
done
